@rootURL = http://localhost:5099

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books
Accept: application/json
###
GET {{rootURL}}/api/books/1
Accept: application/json
###
POST {{rootURL}}/api/books
Content-Type: application/json
###
PUT {{rootURL}}/api/books
Content-Type: application/json
